FROM node:18 AS build-stage


WORKDIR /var/app
COPY frontend/ /var/app
RUN npm install
RUN npm run build


FROM nginx:alpine
# Копируем собранные файлы с предыдущего stage
COPY --from=build-stage /var/app/dist /usr/share/nginx/html

# Копируем конфигурационный файл Nginx (опционально)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]